# Site settings
title: Nikkei Stories 日系物語
email: info@nikkeistories.com
description: > # this means to ignore newlines until "baseurl:"
  Nikkei Stories is an interactive film project that chronicles the history of the Japanese diaspora around the world. The first two phases will be about Nikkei in Vancouver and Steveston, Canada and will be launching in Spring 2015. Stay tuned. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nikkeistories.com" # the base hostname & protocol for your site
twitter_username: nikkeistories
# github_username:  jekyll

# Build settings
markdown: kramdown
